[phases.setup]
nixPkgs = ['nodejs', 'corepack']

[phases.install]
cmds = [
  'corepack enable',
  'corepack prepare pnpm@9.4.0 --activate',
  'pnpm install'
]

[phases.build]
cmds = ['pnpm build']

[start]
cmd = 'pnpm start'
